[package]
name = "rc-zip"
version = "0.0.0"
authors = ["Amos Wenger <amoswenger@gmail.com>"]
edition = "2018"
description = "zip reading and writing"
repository = "https://github.com/rust-compress/rc-zip"
readme = "README.md"
license = "MIT"

keywords = ["zip", "unzip"]
categories = ["compression"]

[badges]
travis-ci = { repository = "rust-compress/rc-zip" }
maintenance = { status = "experimental" }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "5.0.0"
positioned-io = "0.2.2"
pretty-hex = "0.1.0"
hex_fmt = "0.3.0"
